# Generated by Django 4.2.1 on 2023-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('customer', 'customer'), ('seller', 'seller')], default='customer', max_length=8),
        ),
    ]
