# Generated by Django 4.2.1 on 2023-06-03 12:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='fps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('flavour', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateField(auto_now_add=True)),
                ('any_request', models.TextField(blank=True, null=True)),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=8, null=True)),
                ('delivery_type', models.CharField(choices=[('Self', 'Self'), ('DP', 'DP')], default='Self', max_length=4)),
                ('pay_type', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=8)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1)),
                ('order_status', models.CharField(choices=[('NC', 'Not_Confirmed'), ('C', 'Confirmed'), ('R', 'Rejected'), ('F', 'Failed'), ('AB', 'Abendant')], default='NC', max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caketake.customer')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('adult', models.BooleanField(default=False, verbose_name='Adult')),
                ('food_type', models.CharField(choices=[('V', 'Veg'), ('N', 'Non-veg'), ('VN', 'Veg&Non-veg')], max_length=2, null=True)),
                ('Inactive', models.BooleanField(default=False, verbose_name='Inactive')),
                ('created_at', models.DateField(auto_now=True)),
                ('ready', models.TimeField(default='30min')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('tittle', models.CharField(max_length=250, null=True)),
                ('zip', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='addresss', serialize=False, to='caketake.customer')),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=250)),
                ('original_name', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='caketake.product')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='caketake.product')),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='caketake.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='caketake.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caketake.shop'),
        ),
    ]
