# Generated by Django 4.2.1 on 2023-06-05 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='product',
        ),
        migrations.AddField(
            model_name='order_item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='caketake.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='addresss', serialize=False, to='caketake.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='caketake.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ready',
            field=models.TimeField(default='00:30'),
        ),
    ]
