# Generated by Django 4.2.1 on 2023-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0004_fps_floor_alter_fps_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_type',
            field=models.CharField(choices=[('V', 'Veg'), ('NV', 'Non-veg'), ('V&N', 'Veg&Non-veg')], max_length=3),
        ),
    ]
