# Generated by Django 4.2.1 on 2023-06-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0005_alter_product_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fps',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='caketake.product'),
            preserve_default=False,
        ),
    ]
