# Generated by Django 4.2.1 on 2023-06-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0007_collection_alter_fps_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='caketake.collection'),
            preserve_default=False,
        ),
    ]
