# Generated by Django 4.2.1 on 2023-06-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0009_alter_order_food_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
        migrations.RemoveField(
            model_name='product',
            name='Inactive',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
