# Generated by Django 4.2.1 on 2023-06-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0010_alter_order_options_remove_product_inactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='caketake.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='caketake.collection'),
        ),
        migrations.DeleteModel(
            name='order_item',
        ),
    ]
