# Generated by Django 4.2.1 on 2023-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0012_alter_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Self Pickup', 'Self Pickup'), ('DP', 'DP')], default='Self Pickup', max_length=11),
        ),
    ]
