# Generated by Django 4.2.1 on 2023-06-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0013_alter_order_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_collection',
        ),
        migrations.AlterField(
            model_name='fps',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caketake.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Self Pickup', 'Self Pickup'), ('DP', 'DP')], default='Self Pickup', max_length=15),
        ),
        migrations.DeleteModel(
            name='collection',
        ),
    ]
