# Generated by Django 4.2.1 on 2023-06-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0019_alter_address_city_alter_address_landmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='shop',
        ),
    ]
