# Generated by Django 4.2.1 on 2023-06-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0020_remove_address_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresss', to='caketake.shop'),
            preserve_default=False,
        ),
    ]
