# Generated by Django 4.2.1 on 2023-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0022_remove_address_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fps',
            name='making_time',
            field=models.DateTimeField(help_text='HH-MM'),
        ),
    ]
