# Generated by Django 4.2.1 on 2023-06-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0023_alter_fps_making_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fps',
            name='making_time',
            field=models.DateTimeField(),
        ),
    ]
