# Generated by Django 4.2.1 on 2023-06-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0024_alter_fps_making_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='caketake.fps'),
            preserve_default=False,
        ),
    ]
