# Generated by Django 4.2.1 on 2023-06-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0027_shop_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fps',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fps', to='caketake.product'),
        ),
    ]
