# Generated by Django 4.2.1 on 2023-06-11 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0028_alter_fps_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fps',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
