# Generated by Django 4.2.1 on 2023-06-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0029_alter_fps_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='cake/image.img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_images',
            field=models.ImageField(default='', null=True, upload_to='morecake/image.img'),
        ),
    ]
