# Generated by Django 4.2.1 on 2023-06-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caketake', '0032_alter_shop_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='caketake.seller'),
        ),
    ]
